apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-external
  namespace: rook-ceph
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rook-ceph-rgw
    rgw: ceph-object-store
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 172.20.1.25
