# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1qaz@WSX'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my-db:
