apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: default
  annotations:
    purelb.io/addresspool: default
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: 6333
  - name: grpc
    port: 6334
    targetPort: 6334
  type: LoadBalancer
